id: I624E758C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:32:23+00:00'
last_modified: '2022-06-07T20:59:59.134118+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16780
  title: ཐེག་རིམ་མངོན་དུ་བཤད་པའི་མདོ་རྒྱུད་དང་དེའི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DCA5:
      image_group_id: I8LS16789
      title: ''
      total_pages: 154
      order: 1
      base_file: DCA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
