id: P004198
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16780
  title: ཐེག་རིམ་མངོན་དུ་བཤད་པའི་མདོ་རྒྱུད་དང་དེའི་འགྲེལ་པ།
  author: ''
  volumes:
    16777758c04d452d9ff283cec64275ad:
      image_group_id: I8LS16789
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
