id: P004198
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:00:19.152283
source_metadata:
  id: bdr:W8LS16780
  title: ཐེག་རིམ་མངོན་དུ་བཤད་པའི་མདོ་རྒྱུད་དང་དེའི་འགྲེལ་པ།
  author: ''
  volumes:
    16777758c04d452d9ff283cec64275ad:
      image_group_id: I8LS16789
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
